tor-privoxy:
  image: rdsubhas/tor-privoxy-alpine
  expose:
    - 8118
    - 9050
    - 9051
  restart: always
  #name: webir2015_tor_privoxy
  env_file:
    - proxy.env

scrapyd:
  build: ./docker-scrapyd
  expose:
    - 6800
  #name: webir2015_scrapyd
  env_file:
    - database.env
  restart: always
  links:
    - tor-privoxy

web:
  #name: webir2015_web
  restart: always
  build: ./webapp
  expose:
    - 8000
  env_file:
    - database.env
    - proxy.env
  command: /usr/local/bin/gunicorn -w 2 -b :8000 app:app

nginx:
  restart: always
  build: ./nginx/
  ports:
    - "80:80"
  links:
    - web
    - scrapyd
